spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    url: jdbc:mysql://192.168.55.22/appcenter
    password: test1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
