name: CI & CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: YML을 생성합니다.
        run:|
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src
          
    - name: Gradle로 빌드를 진행합니다.
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        
    - name: Jacoco 보고서를 업로드합니다.
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: index
        path: build/jacocoHTML

    - name: 서버로 파일을 SCP합니다.
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        port: 22
        source: "./build/libs/*.jar"
        target: /home/serverking/appcenter-homepage

    - name: SSH를 사용하여 스크립트를 실행합니다.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        port: 22
        script_stop: true
        script: |
          sh /home/serverking/appcenter-homepage/deploy.sh
    
        
